### ISSUE TITLE
Trivia conejitos.

### ISSUE THREAD

**Issue by powertoperu** [AnaSuarez180/Trivia_conejitos#1]
Es recomendable separar las preguntas para que se vea mejor

**Comment by AnaSuarez180** [comment]
¡Solucionado! Si puedes pruébalo otra vez ;)

**Comment by AnaSuarez180** [comment]
Kevin, no sé de qué otra forma contactarte. 
Mándame tu trivia de replit y publícala en github para poder reportar un issue y que ambos podamos enviárselo a silabuz. 
Mi correo es ana.suarez.febres@gmail.com
Por favor, respóndeme por ahí.
